export const contactUsConstant = {
  CREATE_SUBSCRIBE_REQUEST: "CREATE_SUBSCRIBE_REQUEST",
  CREATE_SUBSCRIBE_SUCCESS: "CREATE_SUBSCRIBE_SUCCESS",
  CREATE_SUBSCRIBE_FAILURE: "CREATE_SUBSCRIBE_FAILURE",

  CREATE_CONTACT_REQUEST: "CREATE_CONTACT_REQUEST",
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",
  CREATE_CONTACT_FAILURE: "CREATE_CONTACT_FAILURE",
};
