export const eligibleSubsidyConstant = {
  GET_ELIGIBLE_SUBSIDY_REQUEST: "GET_ELIGIBLE_SUBSIDY_REQUEST",
  GET_ELIGIBLE_SUBSIDY_SUCCESS: "GET_ELIGIBLE_SUBSIDY_SUCCESS",
  GET_ELIGIBLE_SUBSIDY_FAILURE: "GET_ELIGIBLE_SUBSIDY_FAILURE",

  CLEAR_ELIGIBLE_SUBSIDY_SUCCESS: "CLEAR_ELIGIBLE_SUBSIDY_SUCCESS",

  SELECTED_DATA_FOR_ELIGIBLE_SUBSIDY_SUCCESS:
    "SELECTED_DATA_FOR_ELIGIBLE_SUBSIDY_SUCCESS",

  SELECTED_INFORMATION_FOR_ELIGIBLE_SUBSIDY_SUCCESS:
    "SELECTED_INFORMATION_FOR_ELIGIBLE_SUBSIDY_SUCCESS",

  GET_SUBSIDY_REPORT_REQUEST: "GET_SUBSIDY_REPORT_REQUEST",
  GET_SUBSIDY_REPORT_SUCCESS: "GET_SUBSIDY_REPORT_SUCCESS",
  GET_SUBSIDY_REPORT_FAILURE: "GET_SUBSIDY_REPORT_FAILURE",
};
