export const reportManagementConstants = {
  GET_REPORTS_BASED_ON_USER_REQUEST: "GET_REPORTS_BASED_ON_USER_REQUEST",
  GET_REPORTS_BASED_ON_USER_SUCCESS: "GET_REPORTS_BASED_ON_USER_SUCCESS",
  GET_REPORTS_BASED_ON_USER_FAILURE: "GET_REPORTS_BASED_ON_USER_FAILURE",

  SELECTED_CATEGORY_SUCCESS: "SELECTED_CATEGORY_SUCCESS",

  GET_REPORT_BY_REPORT_ID_REQUEST: "GET_REPORT_BY_REPORT_ID_REQUEST",
  GET_REPORT_BY_REPORT_ID_SUCCESS: "GET_REPORT_BY_REPORT_ID_SUCCESS",
  GET_REPORT_BY_REPORT_ID_FAILURE: "GET_REPORT_BY_REPORT_ID_FAILURE",

  DELETE_REPORT_REQUEST: "DELETE_REPORT_REQUEST",
  DELETE_REPORT_SUCCESS: "DELETE_REPORT_SUCCESS",
  DELETE_REPORT_FAILURE: "DELETE_REPORT_FAILURE",

  GENERATE_PDF_BASED_ON_REPORT_ID_REQUEST:
    "GENERATE_PDF_BASED_ON_REPORT_ID_REQUEST",
  GENERATE_PDF_BASED_ON_REPORT_ID_SUCCESS:
    "GENERATE_PDF_BASED_ON_REPORT_ID_SUCCESS",
  GENERATE_PDF_BASED_ON_REPORT_ID_FAILURE:
    "GENERATE_PDF_BASED_ON_REPORT_ID_FAILURE",

  SAVED_PAGE_DATA_SUCCESS: "SAVED_PAGE_DATA_SUCCESS",

  CLEAR_PDF_SUCCESS: "CLEAR_PDF_SUCCESS",
};
