export const reportManagementConstants = {
  GET_REPORTS_BASED_ON_USER_REQUEST: "GET_REPORTS_BASED_ON_USER_REQUEST",
  GET_REPORTS_BASED_ON_USER_SUCCESS: "GET_REPORTS_BASED_ON_USER_SUCCESS",
  GET_REPORTS_BASED_ON_USER_FAILURE: "GET_REPORTS_BASED_ON_USER_FAILURE",

  SELECTED_CATEGORY_SUCCESS: "SELECTED_CATEGORY_SUCCESS",

  GET_REPORT_BY_REPORT_ID_REQUEST: "GET_REPORT_BY_REPORT_ID_REQUEST",
  GET_REPORT_BY_REPORT_ID_SUCCESS: "GET_REPORT_BY_REPORT_ID_SUCCESS",
  GET_REPORT_BY_REPORT_ID_FAILURE: "GET_REPORT_BY_REPORT_ID_FAILURE",
};
