export const userConstants = {
  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",

  USER_GENERATE_OTP_REQUEST: "USER_GENERATE_OTP_REQUEST",
  USER_GENERATE_OTP_SUCCESS: "USER_GENERATE_OTP_SUCCESS",
  USER_GENERATE_OTP_FAILURE: "USER_GENERATE_OTP_FAILURE",

  USER_VALIDATE_OTP_REQUEST: "USER_VALIDATE_OTP_REQUEST",
  USER_VALIDATE_OTP_SUCCESS: "USER_VALIDATE_OTP_SUCCESS",
  USER_VALIDATE_OTP_FAILURE: "USER_VALIDATE_OTP_FAILURE",

  USER_OTP_SAVED_SUCCESS: "USER_OTP_SAVED_SUCCESS",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "LOGOUT",

  USER_REPORT_COUNT_SUCCESS: "USER_REPORT_COUNT_SUCCESS",
};
